basePath: /
host: localhost:8080
info:
  contact: {}
  description: SleekChat backend with authentication and messaging
  title: SleekChat API
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
